version: '3.9'
services:

  redis-cluster-tls-1: &redis-node
    container_name: redis-cluster-tls-1
    image: redis:${REDIS_TAG}
    volumes:
    - ./redis/cluster-tls:/usr/local/etc/redis
    - ../../apps/emqx/etc/certs:/etc/certs
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-tls-2:
    <<: *redis-node
    container_name: redis-cluster-tls-2

  redis-cluster-tls-3:
    <<: *redis-node
    container_name: redis-cluster-tls-3

  redis-cluster-tls-4:
    <<: *redis-node
    container_name: redis-cluster-tls-4

  redis-cluster-tls-5:
    <<: *redis-node
    container_name: redis-cluster-tls-5

  redis-cluster-tls-6:
    <<: *redis-node
    container_name: redis-cluster-tls-6

  redis-cluster-tls-create:
    <<: *redis-node
    container_name: redis-cluster-tls-create
    command: >
      redis-cli
        --cluster create
          redis-cluster-tls-1:6379
          redis-cluster-tls-2:6379
          redis-cluster-tls-3:6379
          redis-cluster-tls-4:6379
          redis-cluster-tls-5:6379
          redis-cluster-tls-6:6379
        --cluster-replicas 1
        --cluster-yes
        --pass "public"
        --no-auth-warning
    depends_on:
      - redis-cluster-tls-1
      - redis-cluster-tls-2
      - redis-cluster-tls-3
      - redis-cluster-tls-4
      - redis-cluster-tls-5
      - redis-cluster-tls-6

