version: '3.9'
services:

  redis-cluster-tls-1: &redis-node
    image: docker.io/bitnami/redis-cluster:${REDIS_TAG}
    container_name: redis-cluster-tls-1
    environment: &redis-node-env
      REDIS_PASSWORD: public
      REDIS_NODES: "redis-cluster-tls-1 redis-cluster-tls-2 redis-cluster-tls-3 redis-cluster-tls-4 redis-cluster-tls-5 redis-cluster-tls-6"
      REDIS_TLS_ENABLED: "yes"
      REDIS_TLS_AUTH_CLIENTS: "no"
      REDIS_TLS_PORT_NUMBER: "6389"
      REDIS_TLS_CERT_FILE: "/etc/certs/redis.crt"
      REDIS_TLS_KEY_FILE: "/etc/certs/redis.key"
      REDIS_TLS_CA_FILE: "/etc/certs/ca.crt"
    volumes:
      - ../../apps/emqx/etc/certs/cacert.pem:/etc/certs/ca.crt
      - ../../apps/emqx/etc/certs/cert.pem:/etc/certs/redis.crt
      - ../../apps/emqx/etc/certs/key.pem:/etc/certs/redis.key
    networks:
      - emqx_bridge

  redis-cluster-tls-2:
    <<: *redis-node
    container_name: redis-cluster-tls-2

  redis-cluster-tls-3:
    <<: *redis-node
    container_name: redis-cluster-tls-3

  redis-cluster-tls-4:
    <<: *redis-node
    container_name: redis-cluster-tls-4

  redis-cluster-tls-5:
    <<: *redis-node
    container_name: redis-cluster-tls-5

  redis-cluster-tls-6:
    container_name: redis-cluster-tls-6
    image: docker.io/bitnami/redis-cluster:${REDIS_TAG}
    depends_on:
      - redis-cluster-tls-1
      - redis-cluster-tls-2
      - redis-cluster-tls-3
      - redis-cluster-tls-4
      - redis-cluster-tls-5
    environment:
      <<: *redis-node-env
      REDISCLI_AUTH: public
      REDIS_CLUSTER_REPLICAS: "1"
      REDIS_CLUSTER_CREATOR: "yes"
    volumes:
      - ../../apps/emqx/etc/certs/cacert.pem:/etc/certs/ca.crt
      - ../../apps/emqx/etc/certs/cert.pem:/etc/certs/redis.crt
      - ../../apps/emqx/etc/certs/key.pem:/etc/certs/redis.key
    healthcheck:
      test: |
        # Convert `cluster info` output into shell variable assignments
        eval "$(
          redis-cli -a "public" --no-auth-warning cluster info | \
            grep "^cluster" | \
            sed -r 's/(\w+):(\w+).*/\1=\2/'
        )"
        [ "$$cluster_state" = "ok" ]      || { echo "cluster state = $$cluster_state"; exit 1; }
        [ "$$cluster_size" -gt 1 ]        || { echo "cluster size = $$cluster_size"; exit 2; }
        [ "$$cluster_known_nodes" -eq 6 ] || { echo "known nodes = $$cluster_known_nodes"; exit 3; }
      interval: 5s
      retries: 3
    networks:
      - emqx_bridge
