name: Functional Verification Tests

on:
  push:
    branches:
      - debug-relup-tests

jobs:
    relup_test_planner:
        runs-on: ubuntu-20.04
        container: emqx/build-env:erl23.2.7.2-emqx-2-ubuntu20.04
        defaults:
          run:
            shell: bash
        outputs:
          matrix: ${{ steps.generate-matrix.outputs.matrix }}
          profile: ${{ steps.profile-and-versions.outputs.profile }}
          vsn: ${{ steps.profile-and-versions.outputs.vsn }}
          broker: ${{ steps.profile-and-versions.outputs.broker  }}
        steps:
        - uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            path: emqx
            fetch-depth: 0
        - name: Get profile and version list
          id: profile-and-versions
          run: |
            cd emqx
            vsn="$(./pkg-vsn.sh)"
            pre_vsn="$(echo $vsn | grep -oE '^[0-9]+.[0-9]')"

            if make emqx-ee --dry-run > /dev/null 2>&1; then
              profile="emqx-ee"
              old_vsns="$(git tag -l "e$pre_vsn.[0-9]" | xargs echo -n | sed "s/e$vsn//")"
              broker="emqx-ee"

            else
              profile="emqx"
              old_vsns="$(git tag -l "v$pre_vsn.[0-9]" | xargs echo -n | sed "s/v$vsn//")"
              broker="emqx-ce"

            fi

            echo "OLD_VSNS=$old_vsns" >> $GITHUB_ENV
            echo "BROKER=$broker" >> $GITHUB_ENV
            echo "PROFILE=$profile" >> $GITHUB_ENV

            echo "::set-output name=vsn::$vsn"
            echo "::set-output name=profile::$profile"
            echo "::set-output name=broker::$broker"


        - name: Generate matrix
          id: generate-matrix
          run: |
            matrix=$(echo -n "$OLD_VSNS" | jq -R -s -c 'split(" ")')
            echo "::set-output name=matrix::$matrix"

        - name: Prepare credentials
          run: |
            if [ "$PROFILE" = "emqx-ee" ]; then
              echo "https://ci%40emqx.io:${{ secrets.CI_GIT_TOKEN }}@github.com" > $HOME/.git-credentials
              git config --global credential.helper store
              echo "${{ secrets.CI_GIT_TOKEN }}" >> emqx/scripts/git-token
            fi

        - name: Build emqx
          run: make -C emqx ${PROFILE}-zip
        - uses: actions/upload-artifact@v2
          with:
            name: emqx_built
            path: emqx/_packages/*/*.zip


    relup_test:
        needs: relup_test_planner
        runs-on: ubuntu-20.04
        container: docker.io/savonarola/emqx-relup-env:4.3
        strategy:
          matrix:
            old_vsn: ${{ fromJson(needs.relup_test_planner.outputs.matrix) }}
        env:
          OLD_VSN: "${{ matrix.old_vsn }}"
          PROFILE: "${{ needs.relup_test_planner.outputs.profile }}"
          VSN: "${{ needs.relup_test_planner.outputs.vsn }}"
          BROKER: "${{ needs.relup_test_planner.outputs.broker }}"
        defaults:
          run:
            shell: bash
        steps:
        - uses: actions/checkout@v2
          with:
            path: emqx
        - uses: actions/download-artifact@v2
          with:
            name: emqx_built
            path: _emqx_built
        - uses: actions/checkout@v2
          with:
            repository: terry-xiaoyu/one_more_emqx
            ref: master
            path: one_more_emqx
        - name: download emqx
          run: |
            set -e -x -u
            mkdir -p _upgrade_base
            cd _upgrade_base
            wget --no-verbose https://s3-us-west-2.amazonaws.com/packages.emqx/$BROKER/$OLD_VSN/$PROFILE-ubuntu20.04-${OLD_VSN#[e|v]}-amd64.zip
        - name: run relup test
          timeout-minutes: 35
          run: |
            set -e -x -u
            mkdir -p packages
            find .
            cp emqx/_emqx_prebuilt/**/*.zip packages
            cp _upgrade_base/*.zip packages
            ls packages
            lux \
            --case_timeout infinity \
            --var PROFILE=$PROFILE \
            --var PACKAGE_PATH=$(pwd)/packages \
            --var ONE_MORE_EMQX_PATH=$(pwd)/one_more_emqx \
            --var VSN="$VSN" \
            --var OLD_VSN="$OLD_VSN" \
            emqx/.ci/fvt_tests/relup.lux
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: emqx_logs
            path: packages/emqx/log/emqx.log.1
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: emqx2_logs
            path: packages/emqx2/log/emqx.log.1
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: lux_logs
            path: lux_logs

