name: Functional Verification Tests

on:
  push:
    branches:
      - debug-relup-tests
      - debug-relup-tests-1

jobs:

    relup_test:
        runs-on: ubuntu-20.04
        container: docker.io/savonarola/emqx-relup-env:4.3
        defaults:
          run:
            shell: bash
        steps:
        - uses: actions/checkout@v2
          with:
            repository: terry-xiaoyu/one_more_emqx
            ref: master
            path: one_more_emqx
        - uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            path: emqx
            fetch-depth: 0
        - name: prepare
          run: |
            echo "PROFILE=emqx" >> $GITHUB_ENV
        - name: get version
          run: |
            broker="emqx-ce"
            edition='opensource'
            echo "BROKER=$broker" >> $GITHUB_ENV
            cd emqx
            vsn="$(./pkg-vsn.sh)"
            echo "VSN=$vsn" >> $GITHUB_ENV
            echo "OLD_VSNS=v4.3.8" >> $GITHUB_ENV
        - name: download emqx
          run: |
            set -e -x -u
            mkdir -p emqx/_upgrade_base
            cd emqx/_upgrade_base
            old_vsns=($(echo $OLD_VSNS | tr ' ' ' '))
            for old_vsn in ${old_vsns[@]}; do
              wget --no-verbose https://s3-us-west-2.amazonaws.com/packages.emqx/$BROKER/$old_vsn/$PROFILE-ubuntu20.04-${old_vsn#[e|v]}-amd64.zip
            done
        - name: build emqx
          run: make -C emqx ${PROFILE}-zip
        - uses: actions/upload-artifact@v2
          with:
            name: emqx
            path: emqx/_packages/**/*.zip
        - name: run relup test
          timeout-minutes: 35
          run: |
            set -e -x -u
            mkdir -p packages
            cp emqx/_packages/${PROFILE}/*.zip packages
            cp emqx/_upgrade_base/*.zip packages
            find .
            lux \
            --case_timeout infinity \
            --var PROFILE=$PROFILE \
            --var PACKAGE_PATH=$(pwd)/packages \
            --var ONE_MORE_EMQX_PATH=$(pwd)/one_more_emqx \
            --var VSN="$VSN" \
            --var OLD_VSN="$OLD_VSNS" \
            emqx/.ci/fvt_tests/relup.lux
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: emqx_logs
            path: packages/emqx/log/emqx.log.1
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: emqx2_logs
            path: packages/emqx2/log/emqx.log.1
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: lux_logs
            path: lux_logs

